#!/usr/bin/env python3
"""Global (user-level) install of the router: hooks for Claude Code / Codex / Antigravity, and the
MCP router server for the hook-less modes (Claude desktop Chat/Cowork, Codex, Antigravity).

    python router/install_hooks.py            # dry run: print what would change
    python router/install_hooks.py --apply    # write it (each changed file gets a .bak first)

Every hook and MCP entry calls a tiny SHIM in ~/.jev-router/bin/ (a path without spaces), which
just runs the real script from this repo. Reason: Antigravity executes hook commands through
`cmd /c`, which mangles quoted paths with spaces ("E:/Coding Projects/..."); the shim also means
moving this repo only requires re-running this installer.

Idempotent: re-running changes nothing if everything is in place. Old entries that pointed
directly at <repo>/router/run_hook.py are replaced by the shim entry.
"""
import json
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HOME = Path.home()
BIN = HOME / ".jev-router" / "bin"
SHIM_HOOK = BIN / "run_hook.py"
SHIM_MCP = BIN / "mcp_server.py"
PY = "python"
APPLY = "--apply" in sys.argv


def fwd(p):
    return str(p).replace("\\", "/")


SHIM_TEMPLATE = '''# generated by {repo}/router/install_hooks.py - runs the real script from the repo
import runpy, sys
target = r"{target}"
sys.argv[0] = target
runpy.run_path(target, run_name="__main__")
'''


def write_if_changed(path, content, label):
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        print(f"[OK]  {label}: up to date")
        return
    print(("[DO]  " if APPLY else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
    if APPLY:
        path.parent.mkdir(parents=True, exist_ok=True)
        if old is not None:
            path.with_name(path.name + ".bak").write_text(old, encoding="utf-8")
        path.write_text(content, encoding="utf-8")


def load(path):
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    return json.loads(path.read_text(encoding="utf-8-sig"))


def is_router_cmd(cmd):
    c = (cmd or "").replace("\\", "/").lower()
    return "router/run_hook.py" in c or ".jev-router/bin/run_hook.py" in c


def hook_cmd(provider, event):
    return f"{PY} {fwd(SHIM_HOOK)} {provider} {event}"


def install_claude_codex(path, provider, matcher, label):
    cfg = load(path)
    groups = cfg.setdefault("hooks", {}).setdefault("UserPromptSubmit", [])
    kept = []
    for g in groups:  # drop every older router entry (repo path or shim), keep foreign hooks
        hs = [h for h in g.get("hooks", []) if not is_router_cmd(h.get("command"))]
        if hs:
            kept.append({**g, "hooks": hs})
    entry = {"hooks": [{"type": "command", "command": hook_cmd(provider, "UserPromptSubmit"), "timeout": 10}]}
    if matcher:
        entry = {"matcher": "*", **entry}
    cfg["hooks"]["UserPromptSubmit"] = kept + [entry]
    write_if_changed(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def install_antigravity_hook(path):
    cfg = load(path)
    for name in list(cfg):  # strip older router handlers from any named hook; drop hooks left empty
        spec = cfg[name]
        if not isinstance(spec, dict) or "PreInvocation" not in spec:
            continue
        spec["PreInvocation"] = [h for h in spec["PreInvocation"] if not is_router_cmd(h.get("command"))]
        if not spec["PreInvocation"]:
            del spec["PreInvocation"]
        if not any(k in spec for k in ("PreToolUse", "PostToolUse", "PreInvocation", "PostInvocation", "Stop")):
            del cfg[name]
    cfg["router"] ={"PreInvocation": [{"type": "command", "command": hook_cmd("antigravity", "PreInvocation"), "timeout": 10}]}
    write_if_changed(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", "antigravity hook")


def mcp_entry():
    return {"command": PY, "args": [fwd(SHIM_MCP)]}


def install_json_mcp(path, label):
    cfg = load(path)
    cfg.setdefault("mcpServers", {})["jev-router"] = mcp_entry()
    write_if_changed(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def install_codex_mcp(path):
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    block = (f'[mcp_servers.jev-router]\ncommand = "{PY}"\nargs = [{json.dumps(fwd(SHIM_MCP))}]\n')
    pat = re.compile(r"\[mcp_servers\.jev-router\]\n(?:(?!\[).*\n?)*", re.M)
    new = pat.sub("", text).rstrip("\n") + "\n\n" + block  # always last: stable across re-runs
    write_if_changed(path, new, "codex MCP")


def main():
    write_if_changed(SHIM_HOOK, SHIM_TEMPLATE.format(repo=fwd(REPO), target=str(REPO / "router" / "run_hook.py")), "hook shim")
    write_if_changed(SHIM_MCP, SHIM_TEMPLATE.format(repo=fwd(REPO), target=str(REPO / "router" / "mcp_server.py")), "MCP shim")
    install_claude_codex(HOME / ".claude" / "settings.json", "claude", False, "claude hook")
    install_claude_codex(HOME / ".codex" / "hooks.json", "codex", True, "codex hook")
    install_antigravity_hook(HOME / ".gemini" / "config" / "hooks.json")
    install_json_mcp(Path(os.environ.get("APPDATA", HOME / "AppData" / "Roaming")) / "Claude" / "claude_desktop_config.json",
                     "claude desktop MCP (Chat/Cowork)")
    install_codex_mcp(HOME / ".codex" / "config.toml")
    install_json_mcp(HOME / ".gemini" / "config" / "mcp_config.json", "antigravity MCP")
    if not APPLY:
        print("\nDry run only. Re-run with --apply to write the changes.")
    else:
        print("\nCodex: changed hooks need a one-time review - run `codex`, then /hooks, and trust the router hook.")


if __name__ == "__main__":
    main()
