#!/usr/bin/env python3
"""Installs (or removes) the router's hooks and MCP server for Claude Code, Codex and Antigravity.

Normally driven by `python install.py`; usable on its own:
    python router/install_hooks.py [--apply] [--providers claude,codex,antigravity] [--uninstall]

Every hook / MCP entry calls a small shim in ~/.jev-router/bin/ that runs the real script from this
repository, so moving the repository only requires re-running the installer. Changed files get a
`.bak` copy first. Idempotent: a second run changes nothing. Entries of other tools are preserved.

Hooks per provider:
    claude       UserPromptSubmit + Stop          (~/.claude/settings.json)
    codex        UserPromptSubmit + Stop          (~/.codex/hooks.json)  - trust once via `codex` -> /hooks
    antigravity  PreInvocation + Stop             (~/.gemini/config/hooks.json)
MCP server "jev-router": Claude desktop (Chat/Cowork), Codex (config.toml), Antigravity (mcp_config.json).
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import platforms as P  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
BIN = P.HOME / ".jev-router" / "bin"
SHIM_HOOK, SHIM_MCP = BIN / "run_hook.py", BIN / "mcp_server.py"
ALL = ("claude", "codex", "antigravity")
SHIM_TEMPLATE = '''# generated by jev-router's installer - runs the real script from the repository
import runpy, sys
target = r"{target}"
sys.argv[0] = target
runpy.run_path(target, run_name="__main__")
'''


class Writer:
    def __init__(self, apply):
        self.apply = apply
        self.changes = 0

    def write(self, path, content, label):
        path = Path(path)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == content:
            print(f"[OK]  {label}: up to date")
            return
        self.changes += 1
        print(("[DO]  " if self.apply else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
        if self.apply:
            path.parent.mkdir(parents=True, exist_ok=True)
            if old is not None:
                path.with_name(path.name + ".bak").write_text(old, encoding="utf-8")
            path.write_text(content, encoding="utf-8")


def fwd(p):
    return str(p).replace("\\", "/")


def load(path):
    path = Path(path)
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    return json.loads(path.read_text(encoding="utf-8-sig"))


def is_router_cmd(cmd):
    c = (cmd or "").replace("\\", "/").lower()
    return "router/run_hook.py" in c or ".jev-router/bin/run_hook.py" in c or fwd(SHIM_HOOK).lower() in c


def hook_cmd(provider, event):
    return f"{P.python_cmd()} {fwd(SHIM_HOOK)} {provider} {event}"


def _strip_router(groups):
    kept = []
    for g in groups or []:
        hs = [h for h in g.get("hooks", []) if not is_router_cmd(h.get("command"))]
        if hs:
            kept.append({**g, "hooks": hs})
    return kept


def claude_codex_hooks(path, provider, w, uninstall=False):
    cfg = load(path)
    hooks = cfg.setdefault("hooks", {})
    for event, matcher in (("UserPromptSubmit", provider == "codex"), ("Stop", False)):
        groups = _strip_router(hooks.get(event))
        if not uninstall:
            entry = {"hooks": [{"type": "command", "command": hook_cmd(provider, event), "timeout": 10}]}
            groups.append({"matcher": "*", **entry} if matcher else entry)
        if groups:
            hooks[event] = groups
        else:
            hooks.pop(event, None)
    if not hooks:
        cfg.pop("hooks", None)
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", f"{provider} hooks")


def antigravity_hooks(path, w, uninstall=False):
    cfg = load(path)
    for name in list(cfg):
        spec = cfg[name]
        if not isinstance(spec, dict):
            continue
        for event in ("PreInvocation", "Stop"):
            if event in spec:
                spec[event] = [h for h in spec[event] if not is_router_cmd(h.get("command"))]
                if not spec[event]:
                    del spec[event]
        if not any(k in spec for k in ("PreToolUse", "PostToolUse", "PreInvocation", "PostInvocation", "Stop")):
            del cfg[name]
    if not uninstall:
        cfg["router"] = {e: [{"type": "command", "command": hook_cmd("antigravity", e), "timeout": 10}]
                         for e in ("PreInvocation", "Stop")}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", "antigravity hooks")


def json_mcp(path, label, w, uninstall=False):
    cfg = load(path)
    servers = cfg.setdefault("mcpServers", {})
    if uninstall:
        servers.pop("jev-router", None)
    else:
        servers["jev-router"] = {"command": P.python_cmd(), "args": [fwd(SHIM_MCP)]}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def codex_mcp(path, w, uninstall=False):
    text = Path(path).read_text(encoding="utf-8") if Path(path).exists() else ""
    pat = re.compile(r"\[mcp_servers\.jev-router\]\n(?:(?!\[).*\n?)*", re.M)
    base = pat.sub("", text).rstrip("\n")
    if uninstall:
        new = base + "\n" if base else ""
    else:
        block = f'[mcp_servers.jev-router]\ncommand = {json.dumps(P.python_cmd())}\nargs = [{json.dumps(fwd(SHIM_MCP))}]\n'
        new = (base + "\n\n" if base else "") + block  # always last: stable across re-runs
    w.write(path, new, "codex MCP")


def install(providers=ALL, apply=False, uninstall=False):
    """Returns the number of files that changed (or would change)."""
    w = Writer(apply)
    if not uninstall:
        w.write(SHIM_HOOK, SHIM_TEMPLATE.format(target=REPO / "router" / "run_hook.py"), "hook shim")
        w.write(SHIM_MCP, SHIM_TEMPLATE.format(target=REPO / "router" / "mcp_server.py"), "MCP shim")
    if "claude" in providers:
        claude_codex_hooks(P.PATHS["claude_settings"], "claude", w, uninstall)
        json_mcp(P.claude_desktop_config(), "claude desktop MCP (Chat/Cowork)", w, uninstall)
    if "codex" in providers:
        claude_codex_hooks(P.PATHS["codex_hooks"], "codex", w, uninstall)
        codex_mcp(P.PATHS["codex_config"], w, uninstall)
    if "antigravity" in providers:
        antigravity_hooks(P.PATHS["agy_hooks"], w, uninstall)
        json_mcp(P.PATHS["agy_mcp"], "antigravity MCP", w, uninstall)
    return w.changes


def main():
    args = sys.argv[1:]
    providers = ALL
    for a in args:
        if a.startswith("--providers="):
            providers = tuple(x for x in a.split("=", 1)[1].split(",") if x in ALL)
    n = install(providers, apply="--apply" in args, uninstall="--uninstall" in args)
    if "--apply" not in args and n:
        print("\nDry run only. Re-run with --apply to write the changes.")


if __name__ == "__main__":
    main()
