#!/usr/bin/env python3
"""Installs or removes the router's hooks and MCP server for Claude Code, Codex and Antigravity.

Every entry calls a shim in ~/.jev-router/bin/, so moving the repository only requires re-running
the installer. A changed file's original is kept once as `<file>.bak`; a config file that is not
valid JSON is reported and left untouched.

    claude       UserPromptSubmit + Stop    ~/.claude/settings.json
    codex        UserPromptSubmit + Stop    ~/.codex/hooks.json (trust once via /hooks)
    antigravity  PreInvocation + Stop       ~/.gemini/config/hooks.json
"""
import json
import re
import sys
from pathlib import Path

from . import platforms as P

REPO = Path(__file__).resolve().parent.parent
BIN = P.HOME / ".jev-router" / "bin"
SHIM_HOOK, SHIM_MCP, SHIM_ROUTE = BIN / "run_hook.py", BIN / "mcp_server.py", BIN / "route.py"
ALL = ("claude", "codex", "antigravity")
SHIM_TEMPLATE = '''# generated by jev-router's installer - runs {target} from the repository
import runpy, sys
sys.path.insert(0, r"{repo}")
{argv}runpy.run_module("{module}", run_name="__main__", alter_sys=True)
'''


def shim(module, command=None):
    """Shim source that runs `module` from this repository; `command` becomes its first argument."""
    argv = f'sys.argv[1:1] = ["{command}"]\n' if command else ""
    target = f"{module} {command}" if command else module
    return SHIM_TEMPLATE.format(target=target, repo=REPO, module=module, argv=argv)


class Writer:
    def __init__(self, apply):
        self.apply = apply
        self.changes = 0

    def write(self, path, content, label):
        path = Path(path)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == content:
            print(f"[OK]  {label}: up to date")
            return
        self.changes += 1
        print(("[DO]  " if self.apply else "[DRY] ") + f"{label}: {'update' if old is not None else 'create'} {path}")
        if self.apply:
            path.parent.mkdir(parents=True, exist_ok=True)
            bak = path.with_name(path.name + ".bak")
            if old is not None and not bak.exists():  # keep the original, pre-jev-router version
                bak.write_text(old, encoding="utf-8")
            path.write_text(content, encoding="utf-8")


def fwd(p):
    return str(p).replace("\\", "/")


class BadConfig(Exception):
    pass


def load(path):
    path = Path(path)
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except ValueError as exc:
        raise BadConfig(f"{path} is not valid JSON ({exc}) - fix it, then re-run") from exc
    if not isinstance(data, dict):
        raise BadConfig(f"{path} does not contain a JSON object - fix it, then re-run")
    return data


def is_router_cmd(cmd):
    c = (cmd or "").replace("\\", "/").lower()
    return ("router/run_hook.py" in c or "jev_router.hooks" in c or ".jev-router/bin/run_hook.py" in c
            or fwd(SHIM_HOOK).lower() in c or fwd(P.short_path(SHIM_HOOK)).lower() in c)


def hook_cmd(provider, event):
    return f"{P.python_cmd()} {P.shell_arg(SHIM_HOOK)} {provider} {event}"


def _strip_router(groups):
    kept = []
    for g in groups or []:
        hs = [h for h in g.get("hooks", []) if not is_router_cmd(h.get("command"))]
        if hs:
            kept.append({**g, "hooks": hs})
    return kept


def claude_codex_hooks(path, provider, w, uninstall=False):
    cfg = load(path)
    hooks = cfg.setdefault("hooks", {})
    for event, matcher in (("UserPromptSubmit", provider == "codex"), ("Stop", False)):
        groups = _strip_router(hooks.get(event))
        if not uninstall:
            entry = {"hooks": [{"type": "command", "command": hook_cmd(provider, event), "timeout": 10}]}
            groups.append({"matcher": "*", **entry} if matcher else entry)
        if groups:
            hooks[event] = groups
        else:
            hooks.pop(event, None)
    if not hooks:
        cfg.pop("hooks", None)
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", f"{provider} hooks")


AGY_EVENTS = ("PreToolUse", "PostToolUse", "PreInvocation", "PostInvocation", "Stop")


def _strip_router_events(spec):
    for event in ("PreInvocation", "Stop"):
        if event in spec:
            spec[event] = [h for h in spec[event] if not is_router_cmd(h.get("command"))]
            if not spec[event]:
                del spec[event]


def antigravity_hooks(path, w, uninstall=False):
    cfg = load(path)
    for spec in cfg.values():
        if isinstance(spec, dict):
            _strip_router_events(spec)
    cfg = {name: spec for name, spec in cfg.items()
           if not isinstance(spec, dict) or any(k in spec for k in AGY_EVENTS)}
    if not uninstall:
        cfg["router"] = {e: [{"type": "command", "command": hook_cmd("antigravity", e), "timeout": 10}]
                         for e in ("PreInvocation", "Stop")}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", "antigravity hooks")


def json_mcp(path, label, w, uninstall=False):
    cfg = load(path)
    servers = cfg.setdefault("mcpServers", {})
    if uninstall:
        servers.pop("jev-router", None)
    else:
        # MCP clients exec "command" directly, without a shell: never shell-quoted
        servers["jev-router"] = {"command": fwd(P.python_exe_windowless()), "args": [fwd(SHIM_MCP)]}
    w.write(path, json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", label)


def codex_mcp(path, w, uninstall=False):
    text = Path(path).read_text(encoding="utf-8") if Path(path).exists() else ""
    # the section ends at the next table or comment line (our generated agents block starts with one)
    pat = re.compile(r"\[mcp_servers\.jev-router\]\n(?:\n|[^\[#\n].*(?:\n|\Z))*")
    block = f'[mcp_servers.jev-router]\ncommand = {json.dumps(fwd(P.python_exe_windowless()))}\nargs = [{json.dumps(fwd(SHIM_MCP))}]\n\n'
    m = pat.search(text)
    if uninstall:
        new = (text[:m.start()] + text[m.end():]) if m else text
    elif m:  # in place: other generated blocks may follow it
        new = text[:m.start()] + block + text[m.end():]
    else:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    w.write(path, new, "codex MCP")


def claude_desktop_mcp(w, uninstall=False):
    """The desktop app rewrites the file from memory: a change made while it runs is lost."""
    before = w.changes
    json_mcp(P.claude_desktop_config(), "claude desktop MCP (Chat/Cowork)", w, uninstall)
    if w.changes > before and P.app_running("Claude"):
        print("[!!]  The Claude desktop app is running: quit it completely (tray icon > Quit) and reopen it, "
              "or it overwrites this change")


def install_shims(w):
    w.write(SHIM_HOOK, shim("jev_router.hooks"), "hook shim")
    w.write(SHIM_MCP, shim("jev_router.mcp_server"), "MCP shim")
    w.write(SHIM_ROUTE, shim("jev_router", "route"), "route shim")


def install(providers=ALL, apply=False, uninstall=False):
    """Number of files that changed (or would change)."""
    w = Writer(apply)
    if not uninstall:
        install_shims(w)
    steps = []
    if "claude" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["claude_settings"], "claude", w, uninstall),
                  lambda: claude_desktop_mcp(w, uninstall)]
    if "codex" in providers:
        steps += [lambda: claude_codex_hooks(P.PATHS["codex_hooks"], "codex", w, uninstall),
                  lambda: codex_mcp(P.PATHS["codex_config"], w, uninstall)]
    if "antigravity" in providers:
        steps += [lambda: antigravity_hooks(P.PATHS["agy_hooks"], w, uninstall),
                  lambda: json_mcp(P.PATHS["agy_mcp"], "antigravity MCP", w, uninstall)]
    for step in steps:
        try:
            step()
        except BadConfig as exc:  # one broken file must not stop the others
            print(f"[FAIL] {exc}")
    return w.changes

